# Site settings
title: Held Lab
description: 'Marine microbial Biogeochemistry and Environmental Proteomics' # this means to ignore newlines until "baseurl:"
permalink: ':title:output_ext'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://proteoceanLab.github.io" # the base hostname & protocol for your site, e.g. http://example.com
logo: "/assets/img/branding/HeldLab_logo_light_newcolor.svg"
logo-icon: "/assets/img/branding/HeldLab_logo_light_newcolor_icon_nobk_lighter.svg" # must be svg
logo-icon-SEO: "/assets/img/branding/HeldLab_logo_light_newcolor_icon_lighter.png" # must be a non SVG file

# Night/Dark mode
# Default mode is "auto", "auto" is for auto nightshift
# (19:00 - 07:00), "manual" is for manual toggle, and
# "on/off" is for default on/off.
#
# Whatever the user's choice is, it will supersede the
# default setting of the site and be kept during the
# visit (session). Only the dark mode setting is "manual",
# it will be always kept on every visit (i.e. no matter
# the browser is closed or not)
night_mode: "auto"

logo-dark: "/assets/img/branding/HeldLab_logo_dark_newcolor.svg"
highlight_theme: syntax-base16.monokai.dark # select a dark theme for the code highlighter if needed

# PI settings
author: Noelle Held # add your name
author-pic: Held_photo.jpg
about-author: Assistant Professor, USC Department of Biological Sciences, Marine and Environmental Biology Section
about-author2: Likes a pretty ion chromatogram, doing yoga, teaching yoga, playing the piano, being at sea
# Contact links
email: nheld@usc.edu # Add lab Email address
phone: # Add lab Phone number
website: https://naheld.github.com # Add lab website
#linkedin: amaynez # Add your Linkedin handle
github: naheld # Add lab Github handle
twitter: '@proteocean' # Add your Twitter handle
#bandcamp: armandomaynez # Add your Bandcamp username
#stackoverflow: stackoverflow # Add your stackoverflow account

# Newsletter
#mailchimp: "https://github.us1.list-manage.com/subscribe/post?u=8ece198b3eb260e6838461a60&amp;id=397d90b5f4"

# Tracker
analytics: G-Z13BVKB890
#fbadmin: ar.maybach

# Paginate
paginate: 6
paginate_path: 'page:num'
words_per_minute: 200

# Comments
comments: utteranc  #[disqus, utteranc]
comments_opts:
  comments_curtain: yes # leave empty to show the disqus embed directly
  repo: # The GitHub repo URL.  https://utteranc.es/
  issue_term: # The GitHub issue label
  label: # The GitHub comments label
  theme: # The GitHub comment's there. e.g. github-dark
  # Disqus
  discus_identifier: # Add your discus identifier

# Build settings
markdown: kramdown
mathjax: true
highlighter: rouge
compress_html:
  clippings: all
  comments: all
  startings: [html, head, body]

# Outputting
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

category_archive:
  type: liquid
  path: /categories/

sass:
  style: compressed

plugins:
  - jekyll-paginate
  - jekyll-feed
  - jekyll-sitemap

collections:
  people:
    output: true

include: [_pages, _people]
exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock", "package-lock.json", "assets/css/sass/"]
